[tool.poetry]
name = "geoinfo"
version = "0.1.0"
description = ""
authors = ["torupa <xpt77@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
geopy = "^2.4.1"
scipy = "^1.15.2"
shapely = "^2.1.0"
pyproj = "^3.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
